In [3]:
#Intro
temp=[12,21,2,32,43,54,3,54]
total=0
for i in temp:#slow
    total+=i
print(total/len(temp))    

27.625


In [7]:
import numpy as np
temp=np.array([1,2,3,4,4,2,3232,2,23,23,2,3,23,2,3])
print(np.mean(temp)) #fast

221.93333333333334


In [8]:
#numpy -> numerical python
list=[1,2,3,4,5]
import numpy as np
arr=np.array([1,2,3,4,5])
print(list)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [9]:
#1D array
import numpy as np
ar1d=np.array([1,2,3,4,5])
print(ar1d)

[1 2 3 4 5]


In [10]:
#2D array
import numpy as np
ar2d=np.array([[1,2],[3,4],[5,6]])
print(ar2d)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
#multi D array
import numpy as np
md=np.array([[[1,2],[1,3]],[[4,5],[6,7]]])
print(md)

[[[1 2]
  [1 3]]

 [[4 5]
  [6 7]]]


In [13]:
###CREATING ARRAYS FROM LISTS
#mp.array(list)
import numpy as np
l=[1,2,3,4]
arr=np.array(l)
print(arr)

[1 2 3 4]


In [17]:
###CREATING ARRAYS WITH DEFAULT VALUES
import numpy as np
#array of zeros: np.zeros((shape))
ar0=np.zeros((3))
print(ar0)
#array of 1s: np.ones((shape))
ar1=np.ones((3,3))
print(ar1)
#array of value: np.full((shape),value)
arv=np.full((2,4),5)
print(arv)
#array of range: np.arange(start,stop,jump)
arr=np.arange(0,10,2)
print(arr)
#identity matrix: np.eye(size)
ari=np.eye(3)
print(ari)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]]
[0 2 4 6 8]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#SHAPE CHECKING
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [19]:
#SIZE CHECKING
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [20]:
#NO. OF DIMENSIONS CHECKING
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [22]:
#DATA TYPE CHECKING
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [23]:
#CHANGING FROM ONE TYPE TO OTHER
#arr.astype(new_type)
import numpy as np
arr=np.array([[1.2,2.4,3.6],[4.8,5.0,6.2]])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)


[[1 2 3]
 [4 5 6]]
int64


In [24]:
#MATHS
# +, -, *, /, //, **, %
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr/2)
print(arr//2)


[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]


In [25]:
#Aggregation functions
import numpy as np
arr=np.array([[1.2,2.4,3.6],[4.8,5.0,6.2]])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

23.2
3.8666666666666667
1.2
6.2
1.6799470891138872
2.822222222222223


In [28]:
###INDEXING AND SLICING
#access
'''
arr[idx] 1d
arr[r,c] 2d
...
'''
import numpy as np
arr=np.array([[1.2,2.4,3.6],[4.8,5.0,6.2]])
print(arr[1,2])
print(arr[-2,-2])

6.2
2.4


In [32]:
'''
slicing
arr[start,end,stop]
'''
import numpy as np
arr=np.array([1.2,2.4,3.6,4.8,5.0,6.2])
print(arr[1:5])
print(arr[:4])
print(arr[::-1])
print(arr[::2])

[2.4 3.6 4.8 5. ]
[1.2 2.4 3.6 4.8]
[6.2 5.  4.8 3.6 2.4 1.2]
[1.2 3.6 5. ]


In [33]:
'''
fancy indexing - select multiple elementts at once
'''
import numpy as np
arr=np.array([1.2,2.4,3.6,4.8,5.0,6.2])
print(arr[[0,3,5]])

[1.2 4.8 6.2]


In [35]:
'''
boolean masking
'''
import numpy as np
arr=np.array([1.2,2.4,3.6,4.8,5.0,6.2])
print(arr[arr>4.0])

[4.8 5.  6.2]


In [43]:
###RESHAPING AND MANIPULATION
'''
arr.reshape(r,c) -> view
'''
import numpy as np
arr=np.array([1.2,2.4,3.6,4.8,5.0,6.2,6.0,3.0])
newarr=arr.reshape(1,1,1,1,2,2,2)
print(newarr)
print(arr)
'''
flattening
arr.ravel() ->view
arr.flatten() ->copy
'''
import numpy as np
arr3=np.array([[1.2,2.4,3.6],[4.8,5.0,6.2]])
ar1=arr3.ravel()
ar2=arr3.flatten()
print(ar1)
print(ar2)
print(arr3)

[[[[[[[1.2 2.4]
      [3.6 4.8]]

     [[5.  6.2]
      [6.  3. ]]]]]]]
[1.2 2.4 3.6 4.8 5.  6.2 6.  3. ]
[1.2 2.4 3.6 4.8 5.  6.2]
[1.2 2.4 3.6 4.8 5.  6.2]
[[1.2 2.4 3.6]
 [4.8 5.  6.2]]


In [61]:
###ADVANCED NUMPY
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
'''
np.insert(array,idx,value,axis=)
0 means vertically,
1 means horizontally,
None means flattened
'''
print(np.insert(arr.astype(float),3,3.5))
print(np.insert(arr1,2,[1,1],axis=0))
print(np.insert(arr2,0,[[0,0],[0,0]],axis=1))

'''
np.append(array,value,axis=)
'''
print(np.append(arr,[1,2,35],axis=0))
print(np.append(arr1,[[1,2]],axis=0))

'''
np.delete(array,idx,axis=)
'''
print(np.delete(arr,2))
print(np.delete(arr1,1,axis=1))

'''
np.concate(array1,array2,axis=)
'''
print(np.concatenate((arr1,arr1),axis=0))
print(np.concatenate((arr1,arr1),axis=1))

[1.  2.  3.  3.5 4.  5.  6.  7.  8. ]
[[1 2]
 [3 4]
 [1 1]
 [5 6]]
[[[0 0]
  [1 2]
  [3 4]]

 [[0 0]
  [5 6]
  [7 8]]]
[ 1  2  3  4  5  6  7  8  1  2 35]
[[1 2]
 [3 4]
 [5 6]
 [1 2]]
[1 2 4 5 6 7 8]
[[1]
 [3]
 [5]]
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]


In [74]:
###STACKING AND SPLITTING
'''
vstack() row wise
hstack() col wise
'''
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))


'''
np.split(arr,no.) equal
np.hsplit()
np.vsplit()
'''
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(np.split(arr,2))
print(np.hsplit(arr,2))
print(np.vsplit(arr,2))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]])]
[array([[[1, 2]],

       [[5, 6]]]), array([[[3, 4]],

       [[7, 8]]])]
[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]])]


In [77]:
###BROADCASTING
###VECTORIZATION and BROADCASTING are a bit same

import numpy as np
arr=np.array([100,200,300,400,500])
ar1=arr*2
print(ar1)
#1D to 2D
vec=np.array([[[1,2,3,4,5],[3,4,5,6,7]]])
res=arr+vec
print(res)


[ 200  400  600  800 1000]
[[[101 202 303 404 505]
  [103 204 305 406 507]]]


In [82]:
###HANDLING MISSING VALUES
#np.nan ans np.inf are values
'''
np.isnan(array) ->bool array
np.isinf(array) ->bool array
np.nan_to_num(array,nan=,posinf=,neginf=)
'''
import numpy as np
arr=np.array([1,2,np.nan,3,np.nan,5])
print(np.isnan(arr))
nums=np.array([1,2,np.inf,3,4,-np.inf])
print(np.isinf(nums))
print(np.nan_to_num(arr,nan=1))
print(np.nan_to_num(nums,posinf=1000,neginf=-1000))

[False False  True False  True False]
[False False  True False False  True]
[1. 2. 1. 3. 1. 5.]
[    1.     2.  1000.     3.     4. -1000.]


In [47]:
###PROJECT TO CLEAN DATA
import pandas as pd
import numpy as np
df=pd.read_csv("Indian_Employee_Data.csv")
df.drop(columns=['Position','State','Joining_Date'],inplace=True)
df.dropna(subset=['Age','Department','Projects_Completed','Overtime_Hours'],inplace=True)
df.replace([np.inf,-np.inf],np.nan,inplace=True)

df['Salary']=df['Salary'].interpolate(method='linear',inplace=False)
df.fillna({'Experience_Years':df['Experience_Years'].mean()},inplace=True)
df.fillna({'Performance_Rating':df['Performance_Rating'].median()},inplace=True)


df.fillna({'Projects_Completed':df['Projects_Completed'].mean().round(),'Overtime_Hours':df['Overtime_Hours'].median()},inplace=True)

df['Salary']=np.where(df['Salary']<0,df['Salary'].mean(),df['Salary'])
df.drop_duplicates(inplace=True)
avg=df['Salary'].mean()
std=df['Salary'].std()
df=df[(df['Salary']>=avg-3*std)&(df['Salary']<=avg+3*std)]
df.to_csv("cleaned_project.csv",index=False)

print('Cleaning complete')

Cleaning complete
